name: ubuntu-cloud-image-changelog
version: '0.13.2'
base: core20
summary: Helpful utility to generate package changelog between two cloud images
description: |
  Helpful utility to generate package changelog between two cloud images
  using their package manifests.

  Usage:
  ubuntu-cloud-image-changelog generate --from-manifest manifest1.manifest --to-manifest manifest2.manifest --from-series=focal --to-series=focal

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  ubuntu-cloud-image-changelog:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
    command: usr/bin/wrapper
    plugs:
      - network
      - home

parts:
  ubuntu-cloud-image-changelog-wrapper:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x wrapper
      snapcraftctl build
    organize:
      wrapper: usr/bin/wrapper
    stage:
      - usr/bin/wrapper

  ubuntu-cloud-image-changelog:
    plugin: python
    python-packages:
      - ubuntu-cloud-image-changelog
